name: check_syntax

# wykonujemy tylko jak zrobimy push na gałąź check_syntax
on:
  push:
    branches:
      - check_syntax

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      # wersje pythona 3.9, 3.10 i 3.11
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # odwołujemy się do listy wersji pythona u góry
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      # wyświetlamy wersję pythona
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      # instalujemy pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      # instalujemy flake8
      - name: Install flake8
        run: python -m pip install flake8
      - name: Run flake8
        run: python -m flake8
